[project]
name = "collectoss-utilities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["collectoss"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
collectoss = { git = "https://github.com/chaoss/CollectOSS", rev = "339edc520e79dd1728ca19255d94a05a4a107df1" }

[project.scripts]
collectoss-utilities = "collectoss_utilities:cli"
