[project]
name = "collectoss-utilities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "collectoss",
]

[tool.uv.sources]
collectoss = { git = "https://github.com/chaoss/CollectOSS", rev = "b19a4fbff0523d49e397a164020f934ab2c868ad" }
